---
title: "Run simulations"
output: html_notebook
---

```{r}
setwd("~/Desktop/Selection_simulations")
rm(list=ls())
library(tidyverse)
library(reticulate)

Models <- import_from_path("Models", path = "./Selection/")

num_generations <- 100
pop_size <- 250
mu <- 0.004
selection <- 0
```

Run neutral Wright-Fisher with mutation
```{r}
aDF <- Models$WrightFisherRun(as.integer(num_generations), as.integer(pop_size), mu, selection, as.integer(pop_size))

aDF %>%
  ggplot(aes(x=generation, y=count, fill=as.factor(variant))) +
  geom_area(position = "stack") +
  theme_classic() +
  theme(legend.position = "none") 
```

Run Moran
```{r}
aDF <- Models$MoranRun(as.integer(num_generations), as.integer(pop_size), mu, selection, as.integer(pop_size))

aDF %>%
  ggplot(aes(x=generation, y=count, fill=as.factor(variant))) +
  geom_area(position = "stack") +
  theme_classic() +
  theme(legend.position = "none")
```

Run Yule - for 1000 generations starting with 1 individual, with a higher mutation rate
```{r}
aDF <- Models$YuleRun(as.integer(1000), as.integer(1), 0.04, selection, as.integer(1))

counts <- 
  aDF %>%
  group_by(generation) %>%
  summarise(n=sum(count))

# normalise counts
aDF %>%
  mutate(freq = count / counts$n[match(generation, counts$generation)]) %>%
  ggplot(aes(x=generation, y=freq, fill=as.factor(variant))) +
  geom_area(position = "stack") +
  theme_classic() +
  theme(legend.position = "none")
```

